# Generated by Django 5.0.6 on 2024-06-25 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('servico', models.CharField(max_length=200)),
                ('data_servico', models.DateField(default=datetime.datetime(2024, 6, 25, 19, 22, 27, 657133))),
                ('data_servico_futuro', models.DateField(default=datetime.datetime(2024, 12, 22, 19, 22, 27, 658133))),
            ],
        ),
    ]
