# Generated by Django 5.0.6 on 2024-06-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_servico',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='data_servico_futuro',
            field=models.DateField(),
        ),
    ]
