# Generated by Django 5.0.6 on 2024-06-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreClient', '0002_alter_client_data_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_servico',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='data_servico_futuro',
            field=models.CharField(max_length=200),
        ),
    ]
