# Generated by Django 5.0.6 on 2024-06-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreClient', '0003_alter_client_data_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_servico',
            field=models.DateField(max_length=200),
        ),
    ]
