# Generated by Django 5.0.6 on 2024-06-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreClient', '0004_alter_client_data_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='servico',
            field=models.CharField(choices=[('ma', 'Manuntenção'), ('lip', 'Limpeza preventiva'), ('li', 'Limpeza')], max_length=200),
        ),
    ]
