# Generated by Django 5.0.6 on 2024-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreClient', '0005_alter_client_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_servico_futuro',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='servico',
            field=models.CharField(choices=[('Manuntenção', 'Manuntenção'), ('Limpeza', 'Limpeza'), ('Limpeza preventiva', 'Limpeza preventiva')], max_length=200),
        ),
    ]
